language: cpp
dist: xenial
os:
  - linux
compiler:
  - gcc
  - clang
env:
  - RUN_TEST=all
  - RUN_TEST=mra CMAKE_EXTRA_OPTIONS="-D ENABLE_GENTENSOR=1"    
matrix:
  exclude:
    - os: linux
      compiler: clang
      env: RUN_TEST=mra CMAKE_EXTRA_OPTIONS="-D ENABLE_GENTENSOR=1"    
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7
    update: true
    packages:
      - gcc-8
      - g++-8
      - gfortran-8
      - libblas-dev
      - liblapack-dev
      - libtbb-dev
# if necessary to debug the install step, move all lines into
# script step and add appropriate debugging analysis to the
# after_failure step e.g. find . -name config.log -exec cat {} ";"
install:
  - ./ci/dep-$TRAVIS_OS_NAME.sh
script:
  - ./ci/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./build/config.log
  - cat ./build/CMakeFiles/CMakeError.log
  - cat ./build/CMakeFiles/CMakeOutput.log
cache: ccache
cache:
  directories:
    - $HOME/mpich
    - $HOME/libxc
    - $HOME/ccache
    - $HOME/cereal
